# Generated by Django 4.2.5 on 2023-10-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_course_price_lesson_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
